{
 "title": "Crypto Price Monitor",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current BTC Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  price,\n  time\nFROM crypto_prices\nWHERE \n  product_id = 'BTC-USD'\n  AND time = (\n    SELECT MAX(time)\n    FROM crypto_prices\n    WHERE product_id = 'BTC-USD'\n  )"
    }
   ]
  },
  {
   "title": "ETH Current Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  price,\n  time\nFROM crypto_prices\nWHERE \n  product_id = 'ETH-USD'\n  AND time = (\n    SELECT MAX(time)\n    FROM crypto_prices\n    WHERE product_id = 'ETH-USD'\n  )"
    }
   ]
  },
  {
   "title": "Cryptocurrency Price Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price AS \"price\",\n  product_id\nFROM crypto_prices\nWHERE\n  time >= NOW() - INTERVAL '1 hour'\n  AND product_id = 'BTC-USD'\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Ethereum Price Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price AS \"ETH Price\"\nFROM crypto_prices\nWHERE\n  time >= NOW() - INTERVAL '1 hour'\n  AND product_id = 'ETH-USD'\nORDER BY time"
    }
   ]
  }
 ]
}